# Generated by Django 2.2.1 on 2019-07-30 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personA', to='persons.Person')),
                ('personB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personB', to='persons.Person')),
            ],
        ),
    ]
